version: '3'

services:

  llm:
    image: ollama/ollama
    network_mode: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  app:
    build: ./app
    network_mode: host
    depends_on:
      - llm

volumes:
  data: {}
