version: '3'

services:
  llm:
    build: ./llm
    network_mode: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  src:
    build: ./src
    network_mode: host
    volumes:
      - ./data:/usr/app/data

volumes:
  data: {}
