version: '3'

services:
  llm:
    build: ./llm
    image: danmyers300/fwgs:llm
    network_mode: host
  api:
    build: ./api
    image: danmyers300/fwgs:api
    depends_on:
      - llm
    network_mode: host
  ui:
    build: ./ui
    image: danmyers300/fwgs:ui
    depends_on:
      - llm
    network_mode: host
