version: '3'

services:
  llm:
    build: ./llm
    image: danmyers300/fwgs:llm
    ports:
      - 11434:11434
  src:
    build: ./src
    image: danmyers300/fwgs:src
    ports:
      - 11434:11434
    depends_on:
      - llm
