services:
  llm:
    image: fwgasket/llm
    build: ./llm
    ports:
      - "11434:11434"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    networks:
      - fwgasketAI

  app:
    image: fwgasket/app
    build: ./app
    ports:
      - "5000:5000"
    depends_on:
      - llm
    networks:
      - fwgasketAI
    volumes:
      - /usr/app/data:/mnt/d/ai_data

networks:
  fwgasketAI:
    driver: bridge

volumes:
  data: