version: '3'

services:

  llm:
    image: ollama/ollama
    network_mode: host

  src:
    build: ./src
    network_mode: host
    depends_on:
      - llm
    volumes:
      - ./data/source_documents:/usr/app/source_documents

volumes:
  data: {}
