version: '3'

services:
  llm:
    build: ./llm
    image: danmyers300/fwgs:llm
    network_mode: host
  src:
    build: ./src
    image: danmyers300/fwgs:src
    depends_on:
      - llm
    network_mode: host
