version: '3'

services:

  llm:
    image: fwgasket/llm
    build: ./llm
    network_mode: "host"
    #deploy:
    #  resources:
    #    reservations:
    #      devices:
    #        - driver: nvidia
    #          count: 1
    #          capabilities: [gpu]

  app:
    image: fwgasket/app
    build: ./app
    network_mode: "host"
    depends_on:
      - llm

volumes:
  data: {}
